language: node_js
node_js:
- '7'
- 6.9.4
notifications:
  slack:
    secure: IwS7GDYTrBaAB7yZonzjgTASVf+33FQ7BClrdsglyKuewEgtx/uo6FwA2q53MeDLhttYopn7H3lblkZEjMu/bXoHa2t3WSsLucY3tyrU3IF7iKcd9vsVq51EsB16ZNE7yJ8+lSWIVvqxECh8lcawcQ5BPvuY6a6xXbKHHYOb+jjHIr9hWnpqWZv9Aegabb21eZ0vfyvIEVWBmJcDyqYGb+frHbDD8H5bKvbU57K2ay4QyTDfE0XPyRdCgEtPoozG9C2OEVtzJs8AEPy+gd4ddo+MYdgOHt1H+sQexdx42VDiFYYe/NkAdCL0A7bZOTRrq25R4VkxM7eXvochl4THsdbJIbeHSIh7CjGUGVtXOBKjgvtW1GEiY7j7SgVZswe2siF1cPUEEh27VboJ9RCEV52NBTg9360C9ru9FK6sCqDeEUZoxSiSuR+bv+FEb3C9eSvWiQB3Yuak9gcAUMGhnMLQtgg1zT9hJCzvdrdeKICglSH6MCrS+WfwT1MxcRyfD3VzOs8jT0F9peGcD4wQyN/jZ49Iv64hCPrtISAEAVY/z6KRm67+JmgzXAEuim6NsSgxt+VDWBNgolVKHCAUT4CD6MMMxbt4N1zsXywBG9RJUA16ie3jiLZG489ZYgn2WgYSJbDqw8xYaiyc4eP3sHPyoJdp1F8r/VC2WH35z9I=
